# Generated by Django 4.2.13 on 2024-07-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('joined_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='short_detail',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
